In [2]:
import torch
import numpy as np

# 텐서 초기화하기

In [ ]:
data = [[1 ,2], [3, 4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


In [6]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)

tensor([[1, 2],
        [3, 4]])


In [9]:
x_ones = torch.ones_like(x_data) # x_data의 속성을 유지합니다.
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # x_data의 속성을 덮어씁니다.
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.9003, 0.6761],
        [0.0148, 0.3727]]) 



In [10]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
print(f"Random Tensor: \n {rand_tensor} \n")
ones_tensor = torch.ones(shape)
print(f"Ones Tensor: \n {ones_tensor} \n")
zeros_tensor = torch.zeros(shape)
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.5385, 0.3481, 0.8382],
        [0.4439, 0.3251, 0.0817]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


# 텐서의 속성(Attribute)

In [12]:
tensor = torch.rand(3,4)
print(tensor)
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

tensor([[0.9737, 0.7369, 0.8039, 0.1272],
        [0.8645, 0.9966, 0.4505, 0.0059],
        [0.9440, 0.5221, 0.8633, 0.8550]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


# 텐서 연산(Operation)

In [ ]:
# transposing, indexing and slicing 등 100가지 이상의 텐서 연산들이 있음.
# 각 연산들은 GPU에서 실행할 수 있음. 텐서 연산이 GPU에서 실행되도록 하려면, 텐서를 GPU로 이동시켜야 함.
if torch.cuda.is_available(): # GPU가 사용 가능한 경우
    tensor = tensor.to('cuda') # 텐서를 GPU로 이동 
                               # 무조건 tenstor = tensor.to('cuda')로 작성하는 것이 좋음. 복사본을 이동시키는 것이므로, 원본 텐서는 CPU에 남아있게 됨.
                               # 하지만 모델의 경우는 다르니 주의할 것. 모델은 GPU로 이동시키면, 모델의 모든 매개변수와 버퍼가 GPU로 이동하게 됨. 따라서 모델을 GPU로 이동시키면, 모델의 모든 매개변수와 버퍼가 GPU로 이동하게 됨.
    print(f"Device tensor is stored on: {tensor.device}") # 텐서가 어디에 저장되어 있는지 확인하는 것이 (변수명).device로 확인할 수 있음. 
                                                          #cuba:0은 첫 번째 GPU를 의미함. cuda:1은 두 번째 GPU를 의미함. CPU는 cpu로 표시됨.


Device tensor is stored on: cuda:0
tensor([[0.9737, 0.7369, 0.8039, 0.1272],
        [0.8645, 0.9966, 0.4505, 0.0059],
        [0.9440, 0.5221, 0.8633, 0.8550]], device='cuda:0')


In [16]:
# Numpy식의 표준 인덱싱과 슬라이싱
tensor = torch.ones(4, 4)
print(tensor)
tensor[:,1] = 0
print(tensor)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [ ]:
# 텐서 합치기
t1 = torch.cat([tensor, tensor, tensor], dim=1) # dim=0은 세로로 이어붙이는 것, dim=1은 가로로 이어붙이는 것
print(t1)
t1 = torch.cat([tensor, tensor, tensor], dim=0) # dim=0은 세로로 이어붙이는 것, dim=1은 가로로 이어붙이는 것
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [21]:
tensor[:,3] = 2
print(tensor)
# 텐서 곱하기
# 요소별 곱(element-wise product)을 계산합니다.
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)}") # 요소별 곱(element-wise product)을 계산합니다.
# 다른 문법
print(f"tensor * tensor \n {tensor * tensor}") # 요소별 곱(element-wise product)을 계산합니다.

tensor([[1., 0., 1., 2.],
        [1., 0., 1., 2.],
        [1., 0., 1., 2.],
        [1., 0., 1., 2.]])
tensor.mul(tensor) 
 tensor([[1., 0., 1., 4.],
        [1., 0., 1., 4.],
        [1., 0., 1., 4.],
        [1., 0., 1., 4.]])
tensor * tensor 
 tensor([[1., 0., 1., 4.],
        [1., 0., 1., 4.],
        [1., 0., 1., 4.],
        [1., 0., 1., 4.]])


In [ ]:
# 두 텐서 간의 행렬 곱(matrix multiplication)을 계산
print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)}") # 두 텐서 간의 행렬 곱(matrix multiplication)을 계산
# 다른 문법
print(f"tensor @ tensor.T \n {tensor @ tensor.T}") # 두 텐서 간의 행렬 곱(matrix multiplication)을 계산
                                                   # 특이하게도 파이썬에서는 @ 연산자가 행렬 곱을 나타냄. 따라서 tensor @ tensor.T는 tensor.matmul(tensor.T)와 동일한 결과를 반환함.
                                                   # Transpose를 하고 곱하는게 특이함. 주의할 것.


tensor.matmul(tensor.T) 
 tensor([[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]])
tensor @ tensor.T 
 tensor([[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]])


In [24]:
# 바꿔치기 연산
print(tensor, "\n")
tensor.add_(5) # tensor에 5를 더하는 연산을 수행합니다.
print(tensor)

tensor([[1., 0., 1., 2.],
        [1., 0., 1., 2.],
        [1., 0., 1., 2.],
        [1., 0., 1., 2.]]) 

tensor([[6., 5., 6., 7.],
        [6., 5., 6., 7.],
        [6., 5., 6., 7.],
        [6., 5., 6., 7.]])


# NumPy 배열로 변환하기

In [25]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy() # 텐서를 NumPy 배열로 변환합니다.
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [29]:
# 텐서의 변경 사항이 numpy 배열에도 반영됩니다.
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

# numpy 배열의 변경 사항이 텐서에도 반영됩니다.
n += 1  # numpy 배열에 1을 더합니다.
print(f"t: {t}")
print(f"n: {n}")

t: tensor([5., 5., 5., 5., 5.])
n: [5. 5. 5. 5. 5.]
t: tensor([6., 6., 6., 6., 6.])
n: [6. 6. 6. 6. 6.]


# NumPy 배열을 텐서로 변환하기

In [30]:
n = np.ones(5)
t = torch.from_numpy(n)

In [31]:
np.add(n, 1, out=n) # numpy 배열에 1을 더합니다.
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
